### PR TITLE
Detect and trigger Alt-Key keyup, fixes #165

### LINKED ISSUE #165: ALT+Function keys freeze keyboard
(Browsers: Firefox 54, IE11)

Steps to reproduce:

- From the demo page, start MSDOS
- Press ALT-F2
- Try typing anything; you will notice nothing registers

Similarly, you can use the Linux 2.6 demo. Press ALT-F2 and then ALT-F1 again to return to the first terminal. Nothing can then be typed in this first terminal.

### PR DESCRIPTION
**Pull request by ErnWong**
Firefox 57 and Edge 41 on Windows (tested on Windows 10) do not emit keyup event for the alt key when the alt key is pressed with other keys, although Firefox on Ubuntu *does* appears to emit the event. Interesting how older versions of Firefox *do* seem to emit the event too. See #165.

This patch is tested on Firefox (Ubuntu Xenial in a VM and Windows 10) and Chrome. Haven't tested on Apple and with other browsers.

Possible bug with the web browsers? If it is, it might be better to close this PR and wait until they fix it rather add noisy code that adapts to their bugs... if we don't mind keeping v86 in a buggy state while we wait that is.

**Update:** Edge Alt keyup sometimes fires, sometimes doesn't. Strange. https://jsbin.com/vocehicipe/6/edit?html,js,output

Related: https://connect.microsoft.com/IE/feedback/details/2513563/no-keyup-event-for-alt-when-used-as-the-only-modifier-key

### CODE REVIEW

**Comment by ErnWong** [comment]
Turns out it is a filed bug with Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1335347
Potentially this one too: https://bugzilla.mozilla.org/show_bug.cgi?id=809410

**Comment by copy** [comment]
The patch looks good and safe, I think we should merge it even if it's a browser bug. Does this also fix #182?

File: src/browser/keyboard.js [hunk 1]
```diff
@@ -325,11 +325,21 @@ function KeyboardAdapter(bus)
 
     function keyup_handler(e)
     {
+        if(!e.altKey && keys_pressed[0x38])
+        {
+            // trigger ALT keyup manually - some browsers don't
```
Comment (copy) [inline src/browser/keyboard.js]: Add a reference to #165

**Comment by ErnWong** [comment]
> Does this also fix #182?

Nope, it does not appear to fix the mouse problem.

**Comment by ErnWong** [comment]
> The patch looks good and safe, I think we should merge it even if it's a browser bug.

Sounds good!

**Comment by copy** [comment]
Thanks!
